### ISSUE TITLE
Server Crash on error occured - OnRequestFailure callback issue

### ISSUE THREAD

**Issue by JohnMagdy** [Southclaws/pawn-requests#6] opened 2018-05-29 15:11 UTC
Hello everybody, so i was trying to Send some kind of JSON Data to my website but unfortunatly it was facing some techincal issues so that it resulted in 500 ERROR and then my server crashed with the following Crash logs: 
```
[29/05/2018 | 17:02:33] [debug] Server crashed due to an unknown error
[29/05/2018 | 17:02:34] [debug] Native backtrace:
[29/05/2018 | 17:02:34] [debug] #0 6c89d48c in ?? () from cpprest_2_10.dll
[29/05/2018 | 17:02:34] [debug] #1 6ca09ee0 in ?? () from plugins\requests.DLL
[29/05/2018 | 17:02:34] [debug] #2 6ca0a1d9 in ?? () from plugins\requests.DLL
[29/05/2018 | 17:02:34] [debug] #3 6ca06d15 in ?? () from plugins\requests.DLL
[29/05/2018 | 17:02:34] [debug] #4 6ca05416 in ?? () from plugins\requests.DLL
[29/05/2018 | 17:02:34] [debug] #5 6ccb62e4 in ?? () from C:\Windows\system32\ucrtbase.DLL
[29/05/2018 | 17:02:34] [debug] #6 76baefac in ?? () from C:\Windows\system32\kernel32.dll
[29/05/2018 | 17:02:34] [debug] #7 76fb3628 in ?? () from C:\Windows\SYSTEM32\ntdll.dll
[29/05/2018 | 17:02:34] [debug] #8 76fb35fb in ?? () from C:\Windows\SYSTEM32\ntdll.dll
[29/05/2018 | 17:02:34] [debug] Registers:
[29/05/2018 | 17:02:34] [debug] EAX: 00000000 EBX: 0863c4d0 ECX: a30e6070 EDX: 083ae728
[29/05/2018 | 17:02:34] [debug] ESI: 0863c4d0 EDI: 002d73e8 EBP: 09d2ffec ESP: 09d2ffdc
[29/05/2018 | 17:02:34] [debug] EIP: 76fb35fb EFLAGS: 00010206
[29/05/2018 | 17:02:34] [debug] Stack:
[29/05/2018 | 17:02:34] [debug] ESP+00000000: 6ccb6290 086bccd8 00000000 00000000
```
and i have already used the `OnRequestFailure` Callback and the callback of the `RequestJSON` Function (the 4th argument)
```
forward OnFinishDSRequest(Request:id, E_HTTP_STATUS:status, Node:node); // the the 4th argument of the RequestJSON Function...
public OnFinishDSRequest(Request:id, E_HTTP_STATUS:status, Node:node) {
    if(id == DS_JSON && _:node != -1)
    {
       new logs[650], Contentlen[600]; JsonStringify(node, Contentlen);
       switch(status)
       {
          case 200,201,202,204: {
             format(logs, sizeof(logs), "TCP Request sent successfully, sent JSON Node Preview: %s\r\n", Contentlen);
          }
          default: {
             format(logs, sizeof(logs), "The server returned an error while fetching the requested data: ERROR %d", _:status);
          }
	   }
         // some action
    }
    return 1;
}
public OnRequestFailure(Request:id, errorCode, errorMessage[], len)
{
   new logs[350];
   if(id == DS_JSON)
   {
      format(logs, sizeof(logs), "The server returned an error while fetching the requested data: %s(ERROR %d)", errorMessage, errorCode);
      // some action
   }
   return 1;
}
```

**Comment by Southclaws** [comment] 2018-05-29 16:29
I'll see if I can reproduce this, not sure if it's caused by the 500, lack of a body or something else. If the request is successful, even with a 500 status, the callback should be called - `OnRequestFailure` is only called when the plugin itself fails.

It would be helpful if you place a print right at the beginning of each callback just to be certain which one is being called.

**Comment by Southclaws** [comment] 2018-05-29 19:51
Could you try this version? It's compiled in debug mode and contains some additional logging:

[Debug.zip](https://github.com/Southclaws/pawn-requests/files/2050470/Debug.zip)

**Comment by JohnMagdy** [comment] 2018-05-29 22:45
Just one new ERROR which says that the URI doesn't contains a hostname...
```
[30/05/2018 | 00:42:41] ERROR: Failed to create new HTTP client: URI must contain a hostname.
[30/05/2018 | 00:42:41] [debug] Server crashed due to an unknown error
[30/05/2018 | 00:42:41] [debug] Native backtrace:
[30/05/2018 | 00:42:41] [debug] #0 611db421 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 00:42:41] [debug] #1 611ae716 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 00:42:41] [debug] #2 611a97a6 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 00:42:41] [debug] #3 611a9993 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 00:42:41] [debug] #4 61b395c0 in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #5 61b38f53 in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #6 61b457bd in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #7 61b618bf in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #8 61b488ea in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #9 61ba7489 in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #10 61b9c2c7 in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #11 61b880e2 in ?? () from plugins\requests.DLL
[30/05/2018 | 00:42:41] [debug] #12 60e67e48 in ?? () from ucrtbased.dll
[30/05/2018 | 00:42:41] [debug] #13 60e67b8b in ?? () from ucrtbased.dll
[30/05/2018 | 00:42:41] [debug] #14 7724efac in ?? () from C:\Windows\system32\kernel32.dll
[30/05/2018 | 00:42:41] [debug] #15 770f3628 in ?? () from C:\Windows\SYSTEM32\ntdll.dll
[30/05/2018 | 00:42:41] [debug] #16 770f35fb in ?? () from C:\Windows\SYSTEM32\ntdll.dll
[30/05/2018 | 00:42:41] [debug] Registers:
[30/05/2018 | 00:42:41] [debug] EAX: 00000000 EBX: 0271c030 ECX: 00000000 EDX: 000000d1
[30/05/2018 | 00:42:41] [debug] ESI: 09aefe2c EDI: 09aefca0 EBP: 09aeffec ESP: 09aeffdc
[30/05/2018 | 00:42:41] [debug] EIP: 770f35fb EFLAGS: 00010246
[30/05/2018 | 00:42:41] [debug] Stack:
[30/05/2018 | 00:42:41] [debug] ESP+00000000: 60e67ae0 0271c030 00000000 00000000
```
my Main Function:
```
DS_SendWebhooksData(receiver[] = "https://www.my-domain.ovh/ds", Node:JSON_DATA = Node:-1)
{
   new Contentlen[600]; JsonStringify(JSON_DATA, Contentlen);
   new RequestsClient:ds_client = RequestsClient(receiver,
      RequestHeaders(
         "Content-Type", "application/json",
         "Content-Length", strlen(Contentlen)
      )
   );
   DS_JSON = RequestJSON(ds_client, "messanger.php", HTTP_METHOD_POST, "OnFinishDSRequest", JSON_DATA,
      .headers = RequestHeaders(
         "Content-Type", "application/json",
         "Content-Length", strlen(Contentlen)
      )
   );
   return 1;
}
```

**Comment by Southclaws** [comment] 2018-05-29 23:11
Ah, so something is going wrong in `RequestsClient`.

One thing you should be doing is checking the value of `ds_client` before using it. This doesn't excuse the crash in the plugin but it's good practice to do so for any returned ID.

Now I know where to look and it's probably just a bad array index because `ds_client` would be `-1` after `RequestsClient` failed.

**Comment by JohnMagdy** [comment] 2018-05-29 23:51
the ds_client isn't valid....  and the DS_JSON var is valid.... huh ??
```
DS_SendWebhooksData(receiver[], Node:JSON_DATA = Node:-1)
{
   new Contentlen[600]; JsonStringify(JSON_DATA, Contentlen);
   new RequestsClient:ds_client = RequestsClient(receiver,
      RequestHeaders(
         "Content-Type", "application/json",
         "Content-Length", strlen(Contentlen)
      )
   );
   printf(_:ds_client == -1 ? ("ds_client: INVALID VAR.") : ("ds_client: VALID VAR."));
   DS_JSON = RequestJSON(ds_client, "messanger.php", HTTP_METHOD_POST, "OnFinishDSRequest", JSON_DATA,
      .headers = RequestHeaders(
         "Content-Type", "application/json",
         "Content-Length", strlen(Contentlen)
      )
   );
   printf(_:DS_JSON == -1 ? ("DS_JSON: INVALID VAR.") : ("DS_JSON: VALID VAR."));
   return 1;
}
```
Output: 
```
[30/05/2018 | 01:49:08] ERROR: Failed to create new HTTP client: URI must contain a hostname.
[30/05/2018 | 01:49:08] ds_client: INVALID VAR.
[30/05/2018 | 01:49:08] DS_JSON: VALID VAR.
[30/05/2018 | 01:49:08] [debug] Server crashed due to an unknown error
[30/05/2018 | 01:49:08] [debug] Native backtrace:
[30/05/2018 | 01:49:08] [debug] #0 56ccb421 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 01:49:08] [debug] #1 56c9e716 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 01:49:08] [debug] #2 56c997a6 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 01:49:08] [debug] #3 56c99993 in ?? () from cpprest_2_10d.dll
[30/05/2018 | 01:49:08] [debug] #4 5e1395c0 in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #5 5e138f53 in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #6 5e1457bd in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #7 5e1618bf in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #8 5e1488ea in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #9 5e1a7489 in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #10 5e19c2c7 in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #11 5e1880e2 in ?? () from plugins\requests.DLL
[30/05/2018 | 01:49:08] [debug] #12 57597e48 in ?? () from ucrtbased.dll
[30/05/2018 | 01:49:08] [debug] #13 57597b8b in ?? () from ucrtbased.dll
[30/05/2018 | 01:49:08] [debug] #14 7724efac in ?? () from C:\Windows\system32\kernel32.dll
[30/05/2018 | 01:49:08] [debug] #15 770f3628 in ?? () from C:\Windows\SYSTEM32\ntdll.dll
[30/05/2018 | 01:49:08] [debug] #16 770f35fb in ?? () from C:\Windows\SYSTEM32\ntdll.dll
[30/05/2018 | 01:49:08] [debug] Registers:
[30/05/2018 | 01:49:08] [debug] EAX: 00000000 EBX: 02a2f3a0 ECX: 00000000 EDX: 003f37c4
[30/05/2018 | 01:49:08] [debug] ESI: 09b1fe2c EDI: 09b1fca0 EBP: 09b1ffec ESP: 09b1ffdc
[30/05/2018 | 01:49:08] [debug] EIP: 770f35fb EFLAGS: 00010246
[30/05/2018 | 01:49:08] [debug] Stack:
[30/05/2018 | 01:49:08] [debug] ESP+00000000: 57597ae0 02a2f3a0 00000000 00000000
```

**Comment by Southclaws** [comment] 2018-05-30 10:43
That's strange, `RequestJSON` should do nothing if the id is invalid:

https://github.com/Southclaws/pawn-requests/blob/master/src/impl.cpp#L85

I will try and reproduce this behaviour shortly. What I don't understand here is that `printf(_:DS_JSON...` is called before the crash itself. Which means all of that code executes fine and doesn't crash. The crash may be from two places:

- Further up the stack, possibly in the call site of `DS_SendWebhooksData`
- The request *is* being sent somehow and the crash happens in another thread

**Comment by Southclaws** [comment] 2018-05-30 12:03
Okay I think this is fixed now, it was a mistake in the code that checked for invalid client IDs.

https://github.com/Southclaws/pawn-requests/releases/tag/0.6.1

Now, if you pass an invalid client ID (such as -1) to `Request` or `RequestJSON` then it won't crash, it'll just return an invalid request ID.

I've also added two new functions for easily checking the validity of both `RequestClient:` and `Request:` values.

**Comment by JohnMagdy** [comment] 2018-05-30 13:19
Thanks that Server Crash Problem is solved :100: and works as well.
Once i solve my site's `500 ERROR` issues will reply with the results of the Data Transfer Proccess

**Closed** 2018-05-30 13:20 UTC
