### ISSUE TITLE
Problem parsing JSON

### ISSUE THREAD

**Issue by Haytam95** [Southclaws/pawn-requests#17] opened 2018-11-22 12:53 UTC
When parsing a received a JSON from Java (Spring) REST service it doesn't receive nothing. I thought it was because of nulls on Json, so i filled them with empty strings and arrays but still.

Java Entity

~~~
@Entity
public class Usuario implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column
  @NotNull
  private String username;

  @Column
  @NotNull
  private String contrasenia;

  @Column
  private String correo;

  @Column
  private Date fechaAlta;

  @Column
  private Float salud;

  @Column
  private Float blindaje;

  @Column
  private Integer energia;

  @Column
  private Integer saciedadHambre;

  @Column
  private Integer conectado;

  @JoinColumn
  @ManyToOne
  private Crew crew;

  @JoinColumn
  @ManyToOne
  private RangoCrew rangoCrew;


  @JoinColumn
  @OneToMany(fetch = FetchType.LAZY)
  private List<Vehiculo> vehiculoList;

  @JoinColumn
  @OneToMany(fetch = FetchType.LAZY)
  private List<Propiedad> propiedadList;

  @JoinColumn
  @OneToMany(fetch = FetchType.LAZY)
  private List<ItemInventario> itemInventarioList;

  @JoinColumn
  @ManyToMany(fetch = FetchType.LAZY)
  private List<Afeccion> afeccionList;
}
~~~

Java REST:

~~~
@PostMapping("findUsuarioByUsername")
  public Usuario findUsuarioByUsername(@RequestBody Map<String, String> body) {

    String username = body.get("username");

    return usuarioRepository.findUsuarioByUsername(username);
  }
~~~

---

JSON comming from service (Not null protected):

~~~
{
    "username": "Elba_Nanero",
    "contrasenia": "lala",
    "correo": null,
    "fechaAlta": null,
    "salud": null,
    "blindaje": null,
    "energia": null,
    "saciedadHambre": null,
    "conectado": 1,
    "crew": null,
    "rangoCrew": null,
    "vehiculoList": null,
    "propiedadList": null,
    "itemInventarioList": null,
    "afeccionList": null
}
~~~

---
Json null protected

~~~
{
    "username": "Elba_Nanero",
    "contrasenia": "lala",
    "correo": "asdasd",
    "fechaAlta": "2018-11-22T13:11:30.996+0000",
    "salud": 0,
    "blindaje": 0,
    "energia": 0,
    "saciedadHambre": 0,
    "conectado": 1,
    "crew": {},
    "rangoCrew": {},
    "vehiculoList": [],
    "propiedadList": [],
    "itemInventarioList": [],
    "afeccionList": []
}
~~~

---

SAMP - Request:

~~~
public OnGameModeInit()
{
client = RequestsClient("http://localhost:8080/", RequestHeaders(
        "Content-Type", "application/json",
        "Accept", "application/json"
   	));
    
    new Node:node = JsonObject("username", JsonString("Elba_Nanero"));
    
	RequestJSON(client, "usuario/findUsuarioByUsername", HTTP_METHOD_POST, "OnServerResponse", node, RequestHeaders("Content-Type", "application/json",
        "Accept", "application/json"));
return 1;

}
~~~

SAMP - Process Response:

~~~
public OnServerResponse(id, status, node) {

	new strResponse[512];
	new strData[128];
	
    JsonGetString(node, "contrasenia", strData);
	format(strResponse, 512, "Recibi: '%s'", strData);
	print(strResponse);
}
~~~

SAMP - Error | Empty
![image](https://user-images.githubusercontent.com/7773130/48904826-700bba80-ee3e-11e8-873e-d955f7eab51f.png)

A little hand please?

Also, the status code is **2** (WTF)

![image](https://user-images.githubusercontent.com/7773130/48905370-28862e00-ee40-11e8-8582-23f07f596fab.png)

------

## Update

After some testing, ~~i found out that only strings are the problem~~. Look at this:

![image](https://user-images.githubusercontent.com/7773130/48906432-31c4ca00-ee43-11e8-8181-e9ed6c9c54cb.png)

~~Float and Integers work fine~~ Neither float and integers are working, they come as "0" always

**Comment by Southclaws** [comment] 2018-11-22 13:57
If you have `curl` available, could you post the output of `curl`ing that endpoint with the `-v` flag? Since *nothing* seems to be working here, I suspect it's some edge case with the details of the response.

If you don't have `curl`, instead modify your code to make use of the basic `Request` function instead of `RequestJSON` and simply print out the response body and check that it's actually the expected JSON payload.

Also, ensure your headers include a `Content-Type: application/json` which I would assume they would since Spring should handle that automatically, but it's good to check just in case.

**Comment by Haytam95** [comment] 2018-11-22 14:18
I just editted my code, i found something a little strange.

![image](https://user-images.githubusercontent.com/7773130/48908041-fc6eab00-ee47-11e8-9b2f-69a93d9b68a7.png)

Strings after response data concatenation aren't showing. Maybe encoding problem?

**Comment by Southclaws** [comment] 2018-11-22 15:16
That first issue you noticed would be the culprit - the response contains invalid characters. If you open the output file in a hex viewer (Notepad++ can do this I think and Sublime has a plugin for it) you'll see the exact binary values.

But it seems like the problem is with the server, not the client.

**Comment by Haytam95** [comment] 2018-11-22 17:02
Just checked characters in response using Postman. It's ok, so i'm out of ideas

![image](https://user-images.githubusercontent.com/7773130/48915900-21224d00-ee5f-11e8-88a5-c4a3b67f958e.png)

![image](https://user-images.githubusercontent.com/7773130/48915921-31d2c300-ee5f-11e8-9d8a-13c7552a67d7.png)

**Comment by Haytam95** [comment] 2018-11-22 17:06
Also running SAMP default HTTP request, it worked ok:

![image](https://user-images.githubusercontent.com/7773130/48916102-b7ef0980-ee5f-11e8-999e-9726c5be0561.png)

![image](https://user-images.githubusercontent.com/7773130/48916107-c1787180-ee5f-11e8-8b54-dc73aac8cef7.png)

**Comment by Southclaws** [comment] 2018-11-23 09:40
Just to make sure: have you seen any error in `OnRequestFailure`?

**Comment by Haytam95** [comment] 2018-11-23 11:45
I was thinking, if there is a way in witch we could debug the plugin locally with breakpoints (Using the source code)? Just to see what happens on the response.

I don't know how to program on C++ or develop SAMP Plugins, but if you give me a few hints i'm sure i'll be able to debug it and find out what's going on.

At this point, i'm pretty sure that:

- **SAMP to Java data is getting fine**
- **Java response is correct and is encoded UTF-8** (tested with Postman)
- **HTTP native SAMP is getting Java data fine**

Do you have something in mind?

**Comment by Haytam95** [comment] 2018-11-24 23:18
> I noticed you used `HTTP_METHOD_POST` in the code, but in the Postman and SA:MP standard HTTP call you used a GET method, is this intentional? Ensure your endpoint can deal with receiving data through a POST method if you need to send data to it. If this is the case, there is still something going wrong with the response not raising an error.

Yeah, it was intentional when i tried default HTTP request SAMP. 

> Another thing that probably won't help here but is good practice is to check the return value of `Request`/`RequestJSON` functions, a non-zero return value indicates an error.
> 
> If none of this helps, I'll do some digging tomorrow.

![image](https://user-images.githubusercontent.com/7773130/48973754-0e0da980-f026-11e8-9731-8c944559ca98.png)

RequestJson is returning 0 and Java service is getting the value ok.

**Comment by Haytam95** [comment] 2018-11-27 11:11
Okay thanks for the update! 

**Waiting for it!**

**Comment by Southclaws** [comment] 2018-11-29 19:32
Update: I have the environment set up and I'm ready to debug, hopefully we can get this bug fixed ASAP!

**Comment by Haytam95** [comment] 2018-11-29 19:33
> As far as I know, it _should_ be a case of installing vcpkg, cpprestsdk, cmake and Visual Studio. I'm currently just awaiting the cpprestsdk installation then I shall try and get the source building.

That's what i tried, but... It didn't go so well, i couldn't make the IDE recognize the libraries and more mayhem.

> If you can provide me with a .jar/.war/.exe to run a simple server with some endpoints, it will help with debugging!

Of course! Today i'm full, but i think tomorrow i'll be able to build a war

**Comment by Haytam95** [comment] 2018-11-29 19:35
> Update: I have the environment set up and I'm ready to debug, hopefully we can get this bug fixed ASAP!

Perhaps it's a good time to review the build environment documentation haha

**Comment by Southclaws** [comment] 2018-11-29 19:38
Yep haha I'm doing that now so I don't forget for next time!

**Comment by Southclaws** [comment] 2018-11-29 20:20
Documentation updated with development environment setup guide: **https://github.com/Southclaws/pawn-requests/blob/master/README.md#development**

**Comment by Southclaws** [comment] 2018-11-29 20:31
So I've realised where the status code 2 is coming from, I encoded error values into the status field when calling `OnRequestFailure`: https://github.com/Southclaws/pawn-requests/blob/master/src/impl.cpp#L116 but the strange thing is the log should display `ERROR: General error: (cause)`

**Comment by Haytam95** [comment] 2018-11-29 23:41
I'm kind on a rush, so i could make a simple Spring application with some services (Couldn't build the war, tomorrow i have three exams at university !)

https://github.com/Haytam95/service_test

Just clone & put it to run in Intellij Idea

**Comment by Haytam95** [comment] 2018-11-29 23:41
Anyway, tomorrow i'll build the war propertly, sorry!!!

**Comment by Haytam95** [comment] 2018-12-04 15:32
Quick update!

I'm having some troubles building the war. For some reason, the service works when running from IDE, but i couldn't deploy the war in a Tomcat.

Did you see the repo (https://github.com/Haytam95/service_test) ? Or are waiting for the war?

I'll try harder to find a solution to the war problem

**Comment by Southclaws** [comment] 2018-12-04 15:38
Yeah I cloned it and ran it in IntelliJ, I couldn't get it to run as it was throwing build errors (I did resolve them but after that, couldn't get it to run for some other reason. I'm at work currently so I can't give you any more details currently)

**Comment by Haytam95** [comment] 2018-12-04 16:02
Don't worry. 

It's my mess haha, i'll fix it and improve documentation to make it run.

Once i update everything, i'll leave a comment

**Comment by Haytam95** [comment] 2018-12-05 11:13
Okay. So this is what i understand: Java is receiving data and cpprestsdk is receiving the response. BUT, it's going trough an exception because "it thinks" something failed, because the headers are different. Am i right?

If they can comunicate, maybe we could try: 

- Match the headers adding annotations to Java server
- Insolate the exception and make it run anyway (if we are certain that the data is not corrupted)

I'll search about how can i play a little with Spring headers and see how it goes. 

I'll wait for more! **Good job!**

**Comment by Southclaws** [comment] 2018-12-05 11:39
With Spring and cpprestsdk both being widely used libraries, I would expect both of them to conform to standards and work fine.

Another thing is I think the current binaries are using cpprestsdk v2.10.1 however the Linux builds use the latest pulled from GitHub so Linux vs Windows may behave differently. This may be worth investigating, if the issue doesn't occur on Linux then it's likely fixed in a later version of cpprestsdk.

**Comment by Haytam95** [comment] 2018-12-05 15:36
Update:

Just tried including Content-Length to spring headers response. **Nothing**

Spring new response with headers:

![image](https://user-images.githubusercontent.com/7773130/49523657-feddf580-f888-11e8-9bea-a9416769ae59.png)

---
Samp new call to service:
![image](https://user-images.githubusercontent.com/7773130/49523994-ab1fdc00-f889-11e8-9dd5-357936525100.png)

---
Samp response handling & console:

![image](https://user-images.githubusercontent.com/7773130/49524274-37320380-f88a-11e8-9a2e-437bd37aaabd.png)



We can discard that it's because of **Content-Length** header.

**Comment by Haytam95** [comment] 2018-12-05 15:40
Also i just pushed the new service & filter that adds the content-length header.

**Comment by Haytam95** [comment] 2018-12-05 16:31
I have a good lead: **CORS**.

https://github.com/Microsoft/cpprestsdk/issues/98

Check this out, i'll take a look at the same but for Spring

**Comment by Haytam95** [comment] 2018-12-10 10:53
Hi there! How's it going? Any news?

**Comment by Southclaws** [comment] 2018-12-10 19:32
Unfortunately I can't get the demo server project to run on Windows: `java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer`

**Comment by Haytam95** [comment] 2018-12-10 19:40
In the repo, there is the .jar compiled. https://github.com/Haytam95/service_test/tree/master/jar

Just install Java, open a CMD console and

~~~
java -jar demo.jar
~~~

**Comment by Southclaws** [comment] 2018-12-10 19:49
Thanks, it's running now.

It seems to be working fine:

```
*** Test OnGetData

{"id":"asd","name":"asdasdasd","moreData":[]}

PASS!
```

Using the following code:

```pawn
#define RUN_TESTS

#include <a_samp>
#include <YSI\y_testing>

#include "requests.inc"

new Request:OnGetData_ID;
main() {
    new RequestsClient:client = RequestsClient("http://localhost:8080", RequestHeaders());
    OnGetData_ID = Request(
        client,
        "testGet",
        HTTP_METHOD_GET,
        "OnGetData",
        .headers = RequestHeaders()
    );
}
forward OnGetData(Request:id, E_HTTP_STATUS:status, data[], dataLen);
public OnGetData(Request:id, E_HTTP_STATUS:status, data[], dataLen) {
    print("*** Test OnGetData\n");

    ASSERT(id == OnGetData_ID);
    ASSERT(status == HTTP_STATUS_OK);
    print(data);

    print("\nPASS!");
}

public OnRequestFailure(Request:id, errorCode, errorMessage[], len) {
    printf("Request %d failed with %d: '%s'", _:id, errorCode, errorMessage);
}
```

**Comment by Haytam95** [comment] 2018-12-10 20:11
![image](https://user-images.githubusercontent.com/7773130/49758718-7606f580-fc9e-11e8-97e1-47ece9fb9156.png)

Dammit, i literally copied your script and run it in my PC and it still refuses to work.

**Comment by Southclaws** [comment] 2018-12-10 20:17
I suppose the latest build has some very minor changes then. I would put this down to a cpprestsdk bug that was fixed in a recent version.

I will provide new binaries for the updated version.

**Comment by Haytam95** [comment] 2018-12-10 20:20
Thanks, i'll wait for your update. I hope we could close this issue, it has been a pain in the ass get to the bug hahahaha

**Comment by Haytam95** [comment] 2018-12-12 18:59
There was any problems with the new release? Or should just download the lastest?

**Comment by Haytam95** [comment] 2018-12-12 20:19
![image](https://user-images.githubusercontent.com/7773130/49896318-bf3b7e80-fe31-11e8-8fef-e7a0fa541696.png)

The plugin doesn't load. There's some kind of trouble with the "entry point of method" bla bla bla

**Comment by ras0219-msft** [comment] 2018-12-13 01:10
In case it's useful, vcpkg can wrap up a binary zip via the export command:
```
>vcpkg export --zip cpprestsdk zlib --triplet x64-windows
```
(other options include 7zip and nuget)

**Comment by Haytam95** [comment] 2018-12-16 14:51
@Southclaws in the dependencies folder you left the old cpprest.dll file (cpprest_2_10). I think that's why i'm getting the error.

Could you provide the correct dll please?

**Comment by Southclaws** [comment] 2018-12-17 15:52
Unfortunately I'm travelling at the moment and don't have my Windows laptop with me. I'm not going to be back until after the new year so maybe someone in the community can do a build for you if it's urgent, sorry!

**Comment by Southclaws** [comment] 2019-01-02 18:45
I've updated the latest release for Windows - the one that didn't work was built using Boost 66 whereas the bug was fixed in Boost 67. The latest release includes Boost 68.

**Comment by Haytam95** [comment] 2019-01-02 21:44
Happy new year! And nice new avatar, by the way

Now it's starting & the request reach fine to the service. **BUT**

![temp](https://user-images.githubusercontent.com/7773130/50613903-eda2fb80-0ebd-11e9-99d2-f8593bb6318d.png)

It can't find the public function in the AMX to retrieve the info. It was working previously (When the data was coming corrupted). Something has changed?

I also tried using the native HTTP request (Just to check for misspelling) and it's calling the public.

Maybe #20 & #21 solution bring a new problem?

**Comment by Southclaws** [comment] 2019-01-03 08:53
There are no other changes between versions, all I did was recompile with newer dependencies: https://github.com/Southclaws/pawn-requests/compare/0.8.4...0.8.5

The changes in #21 are on a different branch because it's a pull request, those changes were made later yesterday evening after releasing the binary. I can't reproduce this issue unfortunately but I'll have a look again later.

**Comment by Southclaws** [comment] 2019-01-05 19:50
0.8.6 has been released which contains the changes for #21 which fixes #20 - it passes all unit tests, let me know if this issue has been resolved.

**Comment by Haytam95** [comment] 2019-01-06 16:03
Yeah... But... hahaha just joking, you nailed it! 

![image](https://user-images.githubusercontent.com/7773130/50738478-31924b00-11b3-11e9-9479-ba9aeec89cf5.png)

It was a tough issue, uh?  Thank you so much for your time and dedication!

**Comment by Southclaws** [comment] 2019-01-06 16:37
Great to hear! 🎉

**Closed by Southclaws** 2019-01-06 16:37 UTC
